name: pycolorbar
channels:
  - conda-forge
dependencies:
  - pyyaml
  - numpy<=1.26.4
  - matplotlib
  - pydantic>=2.0.0
  # Docs
  - jupyter
  - sphinx=5.1.1
  - sphinx-book-theme=1.0.1
  - nbsphinx=0.8.9
  # Testing
  - setuptools
  - pre-commit
  - coverage
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-sugar
  - deepdiff
  - requests-mock
  - pip
